// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNotebook(arg1:string):Promise<void>;

export function GetCurrentWorkspace():Promise<string|Array<string>>;

export function ListNotebooks():Promise<Array<string>>;

export function SaveNotebook(arg1:string,arg2:string):Promise<void>;

export function SelectWorkspaceFolder():Promise<string>;

export function SetCurrentWorkspace(arg1:string):Promise<void>;
