// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNotebook(arg1) {
  return window['go']['main']['App']['DeleteNotebook'](arg1);
}

export function GetCurrentWorkspace() {
  return window['go']['main']['App']['GetCurrentWorkspace']();
}

export function ListNotebooks() {
  return window['go']['main']['App']['ListNotebooks']();
}

export function SaveNotebook(arg1, arg2) {
  return window['go']['main']['App']['SaveNotebook'](arg1, arg2);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function SetCurrentWorkspace(arg1) {
  return window['go']['main']['App']['SetCurrentWorkspace'](arg1);
}
